### ISSUE TITLE
Default path for config sources

### ISSUE THREAD

**Issue by tonybaines** [tonybaines/gestalt#23]
@smithap via email

> It’d be nice if there was some sort of default convention that automatically searches for <classname>.properties in the local directory and/or some other default locations.
> 
> Would maybe avoid have to explicitly code the loading of the file

**Comment by tonybaines** [comment]
This looks easily do-able as a fallback check in `Configurations.CompositeConfigurationBuilder#done`, it feels like it would need to be tightly specified.

Some possibilities/scenarios, perhaps you can comment @smithap;

- Just `.properties` files or XML etc. as well?
- What if there are multiple files? Fail?
    - e.g. XML and `.properties`
- What are sensible defaults
    - places to look (current directory? `./config`? recursive?!)
    - filenames (`config.properties` ? `class-name.properties`?)

**Comment by smithap** [comment]
I think class-name.properties in the current directory as a stating point. Perhaps a simple annotation on the interface class could provide some level of control?

**Comment by tonybaines** [comment]
Fixed in 2.0.5
